version: '3.1'

services:
    wordpress:
        depends_on:
            - db
        image: wordpress
        restart: always
        ports:
            - 8080:80
        environment:
            WORDPRESS_DB_HOST: db
            WORDPRESS_DB_USER: exampleuser
            WORDPRESS_DB_PASSWORD: examplepass
            WORDPRESS_DB_NAME: exampledb
        volumes:
            - ./wordpress:/var/www/html
            - ./php.ini:/usr/local/etc/php/conf.d/php.ini

    db:
        image: mysql:5.7
        restart: always
        environment:
            MYSQL_DATABASE: exampledb
            MYSQL_USER: exampleuser
            MYSQL_PASSWORD: examplepass
            MYSQL_RANDOM_ROOT_PASSWORD: '1'
        volumes:
            - ./db:/var/lib/mysql
        ports:
            - 3306:3306

    cli:
        depends_on:
            - db
            - wordpress
        image: wordpress:cli
        user: xfs
        volumes:
            - ./wordpress:/var/www/html/
        environment:
            WORDPRESS_DB_HOST: db
            WORDPRESS_DB_USER: exampleuser
            WORDPRESS_DB_PASSWORD: examplepass
            WORDPRESS_DB_NAME: exampledb